### ISSUE TITLE
Improved JAVA support for Linux distributions

### ISSUE THREAD

**Issue by Joeran** [Docear/Desktop#410]
About the font problem with open JDK.

Forum: http://www.docear.org/support/forums/docear-support-forums-group3/bug-reports-forum6/docear-v-1-1-stable-release-wont-start-on-linux-thread940/
I've found the solution for openjdk fonts problem. It's antialias problem of freemind or openjdk.
https://wiki.archlinux.org/index.php/Java_Runtime_Environment_Fonts
I've add "export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'" in the beginning of docear.sh. Result is good font render.
It's very rough method to add variable to java environment, but it works. I'm fink that devs should add this variable to docear script if only it starts from openjdk.

and (Email, same user))

I just used an online tutorial and updated and installed the font fixes of open-jdk and the problem is solved up to a degree.
sudo add-apt-repository ppa:no1wantdthisname/openjdk-fontfix
sudo apt-get update
and this is the way to revert it:
sudo apt-get install ppa-purge
sudo ppa-purge ppa:no1wantdthisname/openjdk-fontfix

**Comment by holocronweaver** [comment]
OpenJDK 8 also fixes all rendering issues for me on Ubuntu 15.04.
