### ISSUE TITLE
Doesn't work properly with JRE 8

### ISSUE THREAD

**Issue by KOLANICH** [Docear/Desktop#463]
Hello. I have JRE 8 installed on Win 8.1. Docear doesn't work properly, there a lot of bugs in the error console, console itself cannot be opened (and trying to open it increases count of errors by 80)...

**Comment by buhtz** [comment]
Can you still reproduce the error with Docear 1.2.0.

On Debian unstable JRE8 work well. I would say this issue can be closed.

**Comment by evolve2k** [comment]
Issue over 2 years old. No response from original poster. 
Recommend close.
(Original poster can reopen if they still have an issue)

**Comment by KOLANICH** [comment]
It works. Thank you. Can be closed.
