### ISSUE TITLE
Can not create bibliography

### ISSUE THREAD

**Issue by msjay2604** [Docear/Desktop#474]
To my horror, I attempt to create my bibliography, but I could not.  Control codes says it is there but it is not,  I dragged references, place cursor where I want bibliography to be and nothing is there.

**Comment by GeorgLink** [comment]
Hi msjay2604,

do you still have this issue?
I'd like to help
Can you provide more information, like whether you want to have your bibliography in Word or in Docear?

Best,
Georg

**Comment by msjay2604** [comment]
No.  Thank you for getting back.

**Comment by GeorgLink** [comment]
Okay ;-)

**Comment by buhtz** [comment]
Please close the issue if msjay2604 doesn't need help anymore.

**Comment by evolve2k** [comment]
Looks resolved by users. Recommend close.
