### ISSUE TITLE
Status of that project

### ISSUE THREAD

**Issue by buhtz** [Docear/Desktop#495]
The last commit is from January.

What is the current status of that project?

**Comment by Joeran** [comment]
The current status is "idling". we have no active developers and I am also very busy.

**Comment by buhtz** [comment]
It is ok of course but it should be described somewhere. Looking on the commit history, the PRs and the age and status of the issues the project looks dead. You have to see that from a marketing position. A potential new developer will check things like that and decided then if she/he will contribute or not.

The team looks big. Are there some offical jobs/task for the team members? It looks like you need a project manager who could take care of Issues, Forum, Mailinglist etc. I would say she/he could keep all communication channels open active and clean. This would make a better picture to the public.

No matter if there is active development currently or not.

**Comment by Joeran** [comment]
yes, indeed, docear would need an active project/community manager, and developers. and if i should have more time some day, i might write this on the web page and update the "about/team" web page.
